[server]
port = 8502
address = "localhost"
# For tunneling/debugging, disable CSRF & CORS to accept any origin
# IMPORTANT: revert to stricter settings for production
enableXsrfProtection = false
enableCORS = false


